version: '3.8'
name: exrates
services:
  backend:
    image: exrates/backend:v1.0.0
    build: ./app/backend/
    container_name: exrates-backend
#   ports:
#     - '5126:80'
    networks:
      - exrates-net
    healthcheck:
      test: curl --head --silent --fail 'http://localhost:80/healthcheck' || exit 1
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 2m
  proxy:
    image: exrates/proxy:v1.0.0
    build:
      context: ./app/frontend/
    container_name: exrates-proxy
    ports:
      - '5126:80'
    networks:
      - exrates-net
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: curl --head --silent --fail http://localhost:80/ || exit 1
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 2m
networks:
  exrates-net:
